server:
  port: "18081"
  mode: "release"
  domain: "occont.asia"
  cert_dir: "certs"
  email: "admin@occont.asia"

app:
  version: "1.0.0"
  build_number: "100"
  update_url: ""
  force_update: false

db:
  type: "mysql"
  host: "rm-t4n7n14b44t31w984.mysql.singapore.rds.aliyuncs.com"
  port: 3306
  username: "db_admin"
  password: "Admin@359"
  name: "baby_fans"

wechat:
  app_id: ""
  app_secret: ""

jwt:
  secret: "super_secret_baby_fans_key"
  expire: 24
